### ISSUE TITLE
WPS pixxie dust attack always fails.

### ISSUE THREAD

**Issue by frequencyg** [derv82/wifite2#58] opened 2017-11-25 09:48 UTC
Hello,
I am a kali linux 2017.2 user with an RT2800USB. For eg.
`VODAFONE_WIFI_108 (70:2E:22:87:86:10 @ 24db) WPS Pixie-Dust: Trying PIN:87790405 (Timeout) (runtime:1m7s tries:0 failures:98 lockouts:0)   `

It always fails! Any help?

**Comment by kimocoder** [comment] 2017-11-25 09:50
There is a problem with PixieDust implementated in wifite2, if your cracking WPS, be sure to run "bully"  or "reaver" standalone.

**Comment by frequencyg** [comment] 2017-11-25 10:12
Can you give me a good tutorial or the commands?
Thanks!

**Comment by MisterBianco** [comment] 2017-11-25 19:01
Yeah try: reaver --help

**Comment by derv82** [comment] 2018-03-03 07:59
You're not alone; Wifite 2's WPS attacks are broken right now.

When it's fixed, I will update issue https://github.com/derv82/wifite2/issues/28

Running it manually:

```bash
# Running reaver:
reaver -i INTERFACE -vv -K -c CHANNEL -b BSSID
# Example for channel 11 and interface wlan0mon:
reaver -i wlan0mon -vv -K -c 11 -b AA:BB:CC:DD:EE:FF

# Running bully:
bully --pixiewps -c CHANNEL -b BSSID IFACE
# Example for channel 11 and interface wlan0mon:
bully --pixiewps -c 11 -b AA:BB:CC:DD:EE:FF wlan0mon
```

So follow https://github.com/derv82/wifite2/issues/28 if you want to know when it's fixed. Resolving this as it's a duplicate of https://github.com/derv82/wifite2/issues/28

**Closed by derv82** 2018-03-03 07:59 UTC
